_config.yml

# Site settings
title: ArKdestroy's GitHub Page
email: mattiamonurro1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub Page. This is where I showcase my projects and share my thoughts on various topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ArKdestroy.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
